// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_bam_or_sam
int read_bam_or_sam(std::string bamFileName);
RcppExport SEXP _qckitalign_read_bam_or_sam(SEXP bamFileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type bamFileName(bamFileNameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bam_or_sam(bamFileName));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qckitalign_read_bam_or_sam", (DL_FUNC) &_qckitalign_read_bam_or_sam, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_qckitalign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
