# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Read in a BAM or SAM file. For a BAM file package will need to be
#' linked against zlib.
#' 
#' @param fileName path to SAM or BAM file
#' @return 
#' @export
read_bam_or_sam <- function(bamFileName) {
    .Call('_qckitalign_read_bam_or_sam', PACKAGE = 'qckitalign', bamFileName)
}

